apiVersion: v1
kind: Secret
metadata:
  name: rango-secrets
  namespace: rango-prod
type: Opaque
stringData:
  nextauth-secret: 'SUA_SECRET_AQUI_PELO_MENOS_32_CARACTERES'
  google-client-id: 'SEU_CLIENT_ID'
  google-client-secret: 'SUA_CLIENT_SECRET'
