# 1. ServiceAccount no namespace onde o runner RODA (tools)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-app-delivery-sa
  namespace: tools
---
# 2. Role no namespace que o runner PRECISA ACESSAR (rango-prod)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner-deployer
  namespace: rango-prod
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "replicasets", "pods", "services", "secrets", "configmaps", "persistentvolumeclaims", "ingresses", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# 3. RoleBinding amarrando o SA (do tools) à Role (no rango-prod)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-deployer-binding
  namespace: rango-prod
subjects:
  - kind: ServiceAccount
    name: github-runner-app-delivery-sa
    namespace: tools
roleRef:
  kind: Role
  name: github-runner-deployer
  apiGroup: rbac.authorization.k8s.io
---
# 4. Role no namespace tools para gerenciar pods de CI
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner-manager
  namespace: tools
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/attach", "pods/log", "secrets", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# 5. RoleBinding no tools
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-manager-binding
  namespace: tools
subjects:
  - kind: ServiceAccount
    name: github-runner-app-delivery-sa
    namespace: tools
roleRef:
  kind: Role
  name: github-runner-manager
  apiGroup: rbac.authorization.k8s.io
